### ISSUE TITLE
sending back raw message/justification for renaming?

### ISSUE THREAD

**Issue by prashanthsadasivan** [zerobotlabs/relax#11]
Hey I really like your project, I think it handles a lot of the complexities of scaling up slackbot services, but I noticed a few peculiar design decisions that I wanted to ask about.

It looks like the messages that are put on the events queue have all the fields renamed for some reason ( team_id becomes team_uid, etc). It also looks like particular events are whitelisted via a switch statement in slack/client.go rather than sending back all the messages and letting the client application of the service decide if they want to respond to them. The renaming also means that we can't reference the slack events documentation when trying to see what we get back with events. Was there a particular reason for this decision? 

Along those same lines, I see that the messages sent on the event queue don't contain the original message slack sent, and as a result certain slack event types are missing (i.e. file_shared file_comment, etc). 

I can understand wanting to wanting to append certain metadata to each message (like Provider and stuff), but would you be opposed to sending back the raw payload to the client as well?

I don't mind making these changes, if you agree. But I wanted to get your take on them before just submitting a PR (I recognize that changing key names is a pretty annoying change to deal with from a client's perspective).

Again, hats off to you, this project is really cool, and I'd definitely like to use it!

**Comment by arunthampi** [comment]
hey @prashanthsadasivan sorry didn't get notified of this, I'll get back to you soon on you questions

**Comment by arunthampi** [comment]
hey @prashanthsadasivan so the reason why I changed names is so that I can have a consistent namespace unique to Relax so that Relax can support multiple messaging backends (such as Hipchat or event Facebook Messenger) so it made sense to standardize on names that are not specific to Slack. I think including the payload might significantly add to the message payload but  I understand your frustration though, I make mistakes with names too.

Let me think about this more and see if there is a better way.
