### ISSUE TITLE
Handle 429 too many requests error from Slack

### ISSUE THREAD

**Issue by arunthampi** [zerobotlabs/relax#23]

**Comment by jmanian** [comment]
We just encountered this for the first time.

It started with an error: `msg="error reading message from slack websocket connection" error="read tcp [ip]:[port]->[ip]:[port]: use of closed network connection"`

Relax then tried to restart the client automatically, but it received the same error again in response. It then got into an endless loop of trying to restart and then receiving this error. After 45 seconds of this Slack's rate limiting kicked in and it started to receive 429 for every attempt at restarting.

In order to get out of the loop I had to manually stop the bot, restart the relax server, and then start the bot again.

**Comment by arunthampi** [comment]
@jmanian yes i've been experiencing this too and have been following what you're doing -- hoping to have a fix out soon.

**Comment by arunthampi** [comment]
@jmanian i've been testing this fix: https://github.com/zerobotlabs/relax/pull/27 and it seems to be working fine. will merge into master once i've monitored it for a couple of days (and travis decides to finally build it!)

**Comment by arunthampi** [comment]
closed by #27
